### PR TITLE
Replace amp module with lodash

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by kamilogorek** [comment]
+1

**Comment by lukekarrys** [comment]
+1, tests pass locally. this repo doesnt have a `travis.yml` file so thats why travis isnt passing.

**Comment by lukekarrys** [comment]
Merged and `v0.2.3` tag pushed. Need publishing to npm from @latentflip or @HenrikJoreteg :smile:

**Comment by HenrikJoreteg** [comment]
done @lukekarrys

**Comment by lukekarrys** [comment]
Published as `v0.2.3`

**Pull request merged**
